import gymnasium as gym
from stable_baselines3 import PPO
from lib.settings import *

from lib.RLagent.agent import HybridVehicleEnv

# 1. Instantiate a clean test version of your custom environment
eval_env = HybridVehicleEnv()

# 2. Load your weights (Point it to the BEST model generated by the callback)
# Stable-Baselines3 automatically maps weights to the device specified
model = PPO.load("./ppo_logs/best_model.zip", device="cpu") 

print("Model weights loaded successfully. Starting journey...")

# 3. Standard execution loop
obs, _ = eval_env.reset()
terminated = False
truncated = False

while not (terminated or truncated):
    # Tell the model to stop exploring and use its best deterministic math
    action, _ = model.predict(obs, deterministic=True)
    obs, reward, terminated, truncated, info = eval_env.step(action)

print("Deterministic test run completed. Rendering results...")
print(f"Final SoC: {obs[1]:.2f}, Total Reward: {reward:.2f}")
print(f"distance travelled: {obs[0]*TARGET_DISTANCE_M/1000:.2f} km")

# Render or plot the trip profiles once finished
eval_env.render()

eval_env_deterministic = HybridVehicleEnv()
obs, _ = eval_env_deterministic.reset()

terminated = False
truncated = False

while not (terminated or truncated):
    if obs[1] <= 0.21:
        action = 1
    elif obs[1] >= 0.95:
        action = 0

    obs, reward, terminated, truncated, info = eval_env_deterministic.step(action)

print("Deterministic test run completed. Rendering results...")
print(f"Final SoC: {obs[1]:.2f}, Total Reward: {reward:.2f}")
print(f"distance travelled: {obs[0]*TARGET_DISTANCE_M/1000:.2f} km")

eval_env_deterministic.render()